### ISSUE TITLE
seekToMillis is not working.

### ISSUE THREAD

**Issue by iamsonumalik** [JackDinealKIM/youtube-android-player-helper#2]
I want to seek video to a specific millisecond but seekToMillis() function is not working. When I called this function , state of YoutubeView changes to ENDED.

**Comment by JackDinealKIM** [comment]
seekToMillis() should be sec time.
For example, if you want to seekTo 1min it should be 
seekToMillis(60).
If you seek to over duration it could be end.

Can you  check it again.

**Comment by iamsonumalik** [comment]
yeah , I figured it out.By the way thanks.

**Comment by ymcao** [comment]
@JackDinealKIM  Hi ,how can play   with fullscreen,until now,i have no idea!

**Comment by JackDinealKIM** [comment]
@iamsonumalik 
As far as I know, there is a parameter for fullscreen but it's not good way because it works only when you first play which means only one time so that I don't recommend that way.

So There is a trick.
first, make full screen button
second, when the button click you can change layout and orientation
That's it. easy. good luck!

**Comment by AdamSHurwitz** [comment]
My video does not change at all when `seekToMillis()` is called.

**Comment by adam-hurwitz** [comment]
It's not initially clear where to place `seekToMillis()` in the YouTube lifecycle. I outlined how to handle this method in this [StackOverflow](https://stackoverflow.com/questions/52481759/how-to-handle-youtube-fragment-onsaveinstancestate/52481960#52481960 ) by placing it within the **PlayerStateChangeListener**. The saved instance state can be passed into the inner class that implements the state change listener to handle screen rotation properly.
